name: coral-app-rgki8
services:
- name: backend
  source_dir: /backend  
  build_command: npm install
  run_command: npm start
  environment_slug: node-js
  http_port: 8080
  routes:
  - path: /api/
- name: frontend
  source_dir: /frontend
  build_command: npm run build
  run_command: npm run preview
  environment_slug: node-js
  http_port: 4173
  routes:
  - path: /
  catchall: true
