name: coral-app-rgki8
services:
- name: frontend
  source_dir: /frontend
  build_command: npm run build
  run_command: npm run preview
  environment_slug: node-js
  http_port: 4173
  routes:
  - path: /
- name: backend
  source_dir: /backend  
  build_command: npm install
  run_command: npm start
  environment_slug: node-js
  http_port: 8080
  routes:
  - path: /api/*
  envs:
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: NODE_ENV
    value: production
  - key: FRONTEND_URL
    value: https://coral-app-rgki8.ondigitalocean.app
  - key: FIREBASE_PROJECT_ID
    value: chat-app-9dbff
  - key: FIREBASE_CLIENT_EMAIL
    value: firebase-adminsdk-fbsvc@chat-app-9dbff.iam.gserviceaccount.com
  - key: FIREBASE_PRIVATE_KEY
    value: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC9IT9Uag0E4D4j\nOa89sLk1hQthX/IiIF53GPDARHEJYHKSjbXKJPOdzKXmP5B3ULtkQAf4jFGOM122\nk8XqyGsOmiOiDEj5FJZLm7G8B5a+V2uYLJiHekZl/fzhC35FevRD0LY2BiiPZvjc\n3Au1iEvbV9ln7DJM/qeJyevmr+BPTpyoFfEO7qV1UG+0QEHOccYUN7jUGQOVNyRL\nMV+mZbIsXID1oYOfDdR5t1BcGYGQ93QOf8UCXmkivSQ1UuSFJFI3HxWygubKRO4k\nI5mu/X+F9gSXW88AGQDR8YyLXz+jO2ht0maQdztu6M+BiTt2BRKHA2qiKzwiIs3i\nIDy5+M75AgMBAAECggEAAroNXJFUW3kDsFSTNBmdi/nddIOSfT83+XHau7zo38yc\nDkSchbvzZrel/yw0sCGx9/Or4b+dJ+aR7/FQuc42q+zZPWt9rFipg5DMttQprlga\nkSS4dMCUrgED0bdNlGEdzzH9xIjhchLXHPEPuqfqxxBsziCjx4Qm5HfMrsRjoKUQ\nSCre7TI8UWHE76HOppM4SBlcZdvio/+CCpmPJ/C4TtK7ikTP94ZOMLW7XGmyNswZ\ncwcpMLQz4pYULN2qzGtv5Eak7pgH1HVE6IP0enU+RTXeubQZkw1GxRRslJ2TZ+Fl\nwWQJ2gQ7BAuPUjGpQPm1GBy1D22nGCtRciyJv1jUUQKBgQDjny1neZgPFllniNJG\ny62T3pRxCFgKNcxkUu66iqQy6UZZeZU4jmGJuu+3xV5pKeztKrY841HZEBLUScGE\n+0Cm/anR+Hs+ARPvTxXxkakcb6nKJ4ZOhcJQlZ0B6BmDIlgd4vP+nOXX34e3zJMH\nyUYPUhqfz/gwE83RrO5Vi9N8sQKBgQDUtY3rABOg8IBYBUwaz1Lh5HQ9eYQU3tFj\nyecz5Da+rt+7uDxSBKTrIoFE5fbEr25va1xJIa+S8OjlJx1eS79YzWmxhsP64eMr\n7v+jMY5OK36Ju7WXd11olA+LipvaqCi3JK4uf40uPyDIHlxBy0360p0WPWXxYhvJ\nYC0mK4RoyQKBgGcZDgO0O3956/zNKBEQ6An14t5fnSDixTUbqy2q5jx5FHgqbcA0\nHVG47iMarmyLpNi3Y9uoSsY6VYz560FEXEBG3MhR9+BZtKHL/HByPVq36Pu7c0XV\np/HAEmFusz+GKss+pK1Ke4CPqnVBn8cDD0yZL537ILsF/U9fOIRe1OfBAoGAcSO8\nv/HDfwhNjAQNTflW4ZZticFX0u4NvCFJnB1YTSahFK1TUGDuA6/PyID1N/sEJ7mY\nVcHYLLV9e13Jzj1GIwrnnCjNl2WNOvIeAYS7Z7LU1JgGZ/Fyusx+VD++1Jg7R+b3\nyv3Hb4Deg/M6KTjlWnOqYIj572G62+sPOM1O2ZkCgYAKqd7PTZbIGg18oCty55+7\nCDYDu0Q0CYoEfKGik9yMk0frfGy3fEdM1vYYBrlfuJvW4VBv8dpSEjgUVlU7O0vy\nd9zg4RFMu0Q9WvzSkJRcu0rQECcKjzWybzTrcWcr2guM7uQ3ZvYZrssGl9aNDXt0\nJEiXiqs9X/LfpZiCUoikEQ==\n-----END PRIVATE KEY-----\n"
