// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMxBX-tXmxOAQ3NTZyN_Y08phmPDzGY_I',
    appId: '1:852481229290:web:bfea05eafb3ad2eaeef293',
    messagingSenderId: '852481229290',
    projectId: 'chat-app-9dbff',
    authDomain: 'chat-app-9dbff.firebaseapp.com',
    storageBucket: 'chat-app-9dbff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMxBX-tXmxOAQ3NTZyN_Y08phmPDzGY_I',
    appId: '1:852481229290:android:bfea05eafb3ad2eaeef293',
    messagingSenderId: '852481229290',
    projectId: 'chat-app-9dbff',
    storageBucket: 'chat-app-9dbff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOpbjS-dL7l4xmATmO_U8U9dUgzOEHT7E',
    appId: '1:852481229290:ios:66a4dd9cc68899f6eef293',
    messagingSenderId: '852481229290',
    projectId: 'chat-app-9dbff',
    storageBucket: 'chat-app-9dbff.firebasestorage.app',
    iosClientId: '852481229290-pnh92ak8649905m3abi4da9ghtovllln.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.mobile2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOpbjS-dL7l4xmATmO_U8U9dUgzOEHT7E',
    appId: '1:852481229290:ios:66a4dd9cc68899f6eef293',
    messagingSenderId: '852481229290',
    projectId: 'chat-app-9dbff',
    storageBucket: 'chat-app-9dbff.firebasestorage.app',
    iosClientId: '852481229290-pnh92ak8649905m3abi4da9ghtovllln.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.mobile2',
  );
}